version: '3.8'

services:
  frontend:
    build:
      context: ./code-execution-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./code-execution-backend
    ports:
      - "5000:5000"
    volumes:
      - ./code-execution-backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
